name: Cypress Tests

on:
  push:
    branches:
      - main

jobs:
  cypress-run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install

      - name: Run Cypress tests
        run: npx cypress test run --headed

      - name: Upload Cypress test results to Cypress Dashboard
        run: npx cypress test run --headed --record --key ${{ secrets.CYPRESS_RECORD_KEY }}
